# Generated by Django 2.1.3 on 2018-11-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
