# Generated by Django 2.1.3 on 2018-11-08 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20181108_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('login_name', models.CharField(max_length=100)),
                ('login_pass', models.CharField(max_length=100)),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
