# Generated by Django 2.1.3 on 2018-11-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loginpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginpass',
            name='url',
            field=models.URLField(),
        ),
    ]
